type: gift

extractor: "VanillaLightCNN"
embedder: "BilinearGCNN"

model_dir: "data/model/GIFT-stage2-pretrain"
step: -1

sample_scale_begin: 0
sample_scale_inter: 0.5 # 0.70716
sample_scale_num: 5 # 6
sample_rotate_begin: -90
sample_rotate_inter: 45 # 30
sample_rotate_num: 5   # 7

hem_interval: 16